
spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/mysql?serverTimezone=Hongkong&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=CONVERT_TO_NULL
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    dbcp2:
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      validation-query: SELECT 1 FROM DUAL
      time-between-eviction-runs-millis: 300000
      min-evictable-idle-time-millis: 1800000
      pool-prepared-statements: true
      soft-min-evictable-idle-time-millis: 300000
      min-idle: 1
      max-wait-millis: 60000
      initial-size: 1
      max-total: 20
    hikari:
      maximum-pool-size: 20
    tomcat:
      time-between-eviction-runs-millis: 3000
  jackson:
    #日期格式化
    date-format: yyyy-MM-dd HH:mm:ss
    serialization:
      #格式化输出
      indent_output: true
      #忽略无法转换的对象
      fail_on_empty_beans: false
    #设置空如何序列化
    defaultPropertyInclusion: NON_EMPTY
    deserialization:
      #允许对象忽略json中不存在的属性
      fail_on_unknown_properties: false
    parser:
      #允许出现特殊字符和转义符
      allow_unquoted_control_chars: true
      #允许出现单引号
      allow_single_quotes: true
    time-zone: Hongkong
mybatis:
  type-aliases-package: com.example.demo.entity
  mapper-locations: com/example/demo/mapper/*.xml
  configuration:
    mapUnderscoreToCamelCase: true
    logImpl: org.apache.ibatis.logging.stdout.StdOutImpl
    typeAliasesPackage: com.jsptpd.gayg.modules

server:
  port: 8089
  ssl:
    key-store: michael.keystore
    key-store-password: test1234
    keyStoreType: JKS
    keyAlias: testkey

logging:
  level:
    root: info
  config: classpath:logback.xml
  path: /home/bus

